name: womens_script_transliterator
description: A program to transliterate English text to the Women's Script featured in the Stormlight Archive novels.

environment:
  sdk: '>=2.13.0-48.0.dev <3.0.0'

dev_dependencies:
  intl: ^0.16.1
  test: ^1.14.4
