name: womens_script_transliterator
description: A program to transliterate English text to the Women's Script featured in the Stormlight Archive novels.

issue_tracker: https://github.com/MichaelFenwick/WomensScriptTransliterator/issues

repository: https://github.com/MichaelFenwick/WomensScriptTransliterator

environment:
  sdk: '>=3.5.0'

dependencies:
  epubx:
    git: git@github.com:MichaelFenwick/epubx.dart.git
  path: ^1.9.0
  universal_html: ^2.2.4
  web: ^1.1.0
  xml: ^6.4.2

dev_dependencies:
  test: ^1.25.7
