name: womens_script_transliterator
description: A program to transliterate English text to the Women's Script featured in the Stormlight Archive novels.

issue_tracker: https://github.com/MichaelFenwick/WomensScriptTransliterator/issues

repository: https://github.com/MichaelFenwick/WomensScriptTransliterator

environment:
  sdk: '>=3.5.0'

dependencies:
  epubx: ^4.0.0
  path: ^1.8.0
  xml: ^6.4.2

dev_dependencies:
  test: ^1.25.7
